/*
 * JanelaSobre.java
 */

package interpolmate;

import org.jdesktop.application.Action;

public class JanelaSobre extends javax.swing.JDialog {

    public JanelaSobre(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(BotaoFechar);
    }

    @Action public void closeAboutBox() {
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoFechar = new javax.swing.JButton();
        javax.swing.JLabel LabelTitulo = new javax.swing.JLabel();
        javax.swing.JLabel LabelAluno = new javax.swing.JLabel();
        javax.swing.JLabel LabelAluno2 = new javax.swing.JLabel();
        javax.swing.JLabel LabelRA = new javax.swing.JLabel();
        javax.swing.JLabel LabelRA2 = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
        javax.swing.JLabel LabelAluno1 = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel LabelRA1 = new javax.swing.JLabel();
        javax.swing.JLabel LabelRA3 = new javax.swing.JLabel();
        javax.swing.JLabel LabelAluno3 = new javax.swing.JLabel();
        javax.swing.JLabel LabelAluno4 = new javax.swing.JLabel();
        javax.swing.JLabel LabelRA4 = new javax.swing.JLabel();
        javax.swing.JLabel LabelRA5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(interpolmate.InterpolMate.class).getContext().getResourceMap(JanelaSobre.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(340, 325));
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(interpolmate.InterpolMate.class).getContext().getActionMap(JanelaSobre.class, this);
        BotaoFechar.setAction(actionMap.get("closeAboutBox")); // NOI18N
        BotaoFechar.setText(resourceMap.getString("BotaoFechar.text")); // NOI18N
        BotaoFechar.setName("BotaoFechar"); // NOI18N

        LabelTitulo.setFont(LabelTitulo.getFont().deriveFont(LabelTitulo.getFont().getStyle() | java.awt.Font.BOLD, LabelTitulo.getFont().getSize()+4));
        LabelTitulo.setText(resourceMap.getString("Application.title")); // NOI18N
        LabelTitulo.setName("LabelTitulo"); // NOI18N

        LabelAluno.setFont(LabelAluno.getFont().deriveFont(LabelAluno.getFont().getStyle() | java.awt.Font.BOLD));
        LabelAluno.setText(resourceMap.getString("LabelAluno.text")); // NOI18N
        LabelAluno.setName("LabelAluno"); // NOI18N

        LabelAluno2.setText(resourceMap.getString("Application.vendor")); // NOI18N
        LabelAluno2.setName("LabelAluno2"); // NOI18N

        LabelRA.setFont(LabelRA.getFont().deriveFont(LabelRA.getFont().getStyle() | java.awt.Font.BOLD));
        LabelRA.setText(resourceMap.getString("LabelRA.text")); // NOI18N
        LabelRA.setName("LabelRA"); // NOI18N

        LabelRA2.setText(resourceMap.getString("Application.homepage")); // NOI18N
        LabelRA2.setName("LabelRA2"); // NOI18N

        appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
        appDescLabel.setName("appDescLabel"); // NOI18N

        LabelAluno1.setFont(LabelAluno1.getFont().deriveFont(LabelAluno1.getFont().getStyle() | java.awt.Font.BOLD));
        LabelAluno1.setText(resourceMap.getString("LabelAluno1.text")); // NOI18N
        LabelAluno1.setName("LabelAluno1"); // NOI18N

        appDescLabel1.setText(resourceMap.getString("appDescLabel1.text")); // NOI18N
        appDescLabel1.setName("appDescLabel1"); // NOI18N

        LabelRA1.setFont(LabelRA1.getFont().deriveFont(LabelRA1.getFont().getStyle() | java.awt.Font.BOLD));
        LabelRA1.setText(resourceMap.getString("LabelRA1.text")); // NOI18N
        LabelRA1.setName("LabelRA1"); // NOI18N

        LabelRA3.setText(resourceMap.getString("LabelRA3.text")); // NOI18N
        LabelRA3.setName("LabelRA3"); // NOI18N

        LabelAluno3.setFont(LabelAluno3.getFont().deriveFont(LabelAluno3.getFont().getStyle() | java.awt.Font.BOLD));
        LabelAluno3.setText(resourceMap.getString("LabelAluno3.text")); // NOI18N
        LabelAluno3.setName("LabelAluno3"); // NOI18N

        LabelAluno4.setText(resourceMap.getString("LabelAluno4.text")); // NOI18N
        LabelAluno4.setName("LabelAluno4"); // NOI18N

        LabelRA4.setText(resourceMap.getString("LabelRA4.text")); // NOI18N
        LabelRA4.setName("LabelRA4"); // NOI18N

        LabelRA5.setFont(LabelRA5.getFont().deriveFont(LabelRA5.getFont().getStyle() | java.awt.Font.BOLD));
        LabelRA5.setText(resourceMap.getString("LabelRA5.text")); // NOI18N
        LabelRA5.setName("LabelRA5"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTitulo)
                            .addComponent(appDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelRA)
                                    .addComponent(LabelAluno1)
                                    .addComponent(LabelAluno))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(appDescLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(LabelRA3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelRA2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                    .addComponent(LabelAluno2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(LabelAluno4, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotaoFechar)
                        .addGap(44, 44, 44))
                    .addComponent(LabelRA1)
                    .addComponent(LabelAluno3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(LabelRA4, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                            .addComponent(LabelRA5))
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appDescLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAluno1)
                    .addComponent(appDescLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAluno2)
                    .addComponent(LabelAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAluno3)
                    .addComponent(LabelAluno4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRA)
                    .addComponent(LabelRA2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelRA1)
                    .addComponent(LabelRA3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelRA5)
                    .addComponent(LabelRA4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(BotaoFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFechar;
    // End of variables declaration//GEN-END:variables
    
}
